<?php
Route::post(':version/user_login','api/:version.token/token');
Route::post(':version/userInfo','api/:version.user/details');//获取用户信息详情
Route::post(':version/userQrCode','api/:version.user/qrCode');//获取用户分销小程序二维码
Route::post(':version/goodsList','api/:version.goods/index');//获取商品列表
Route::post(':version/goodsInfo','api/:version.goods/details');//获取商品详情
Route::post(':version/config','api/:version.config/getConfig');//获取系统配置
Route::post(':version/user_cart','api/:version.cart/index');//获取用户购物车列表
Route::post(':version/cart_create','api/:version.cart/create');//加入购物车
Route::post(':version/cart_update_num','api/:version.cart/updateNum');//增加减少购物车数量
Route::post(':version/cart_delete','api/:version.cart/delete');//删除购物车数据
Route::post(':version/order_create','api/:version.order/create');//提交订单
Route::post(':version/check_order','api/:version.order/check');//校验提交订单
Route::post(':version/order_details','api/:version.order/details');//订单详情
Route::post(':version/order_list','api/:version.order/index');//订单列表
Route::post(':version/cancel_order','api/:version.order/cancel');//订单取消
Route::post(':version/cancel_order','api/:version.order/cancel');//订单取消
Route::post(':version/delete_order','api/:version.order/delete');//订单删除
Route::post(':version/confirmGoods_order','api/:version.order/confirmGoods');//订单确认收货
Route::post(':version/address','api/:version.address/index');//用户收货地址列表
Route::post(':version/details_address','api/:version.address/details');//收货地址详情
Route::post(':version/update_address','api/:version.address/update');//更新收货地址
Route::post(':version/create_address','api/:version.address/create');//创建收货地址
Route::post(':version/delete_address','api/:version.address/delete');//删除收货地址
Route::post(':version/isDefault_address','api/:version.address/isDefault');//设置默认收货地址
Route::post(':version/getDefault_address','api/:version.address/getDefault');//获取默认收货地址
Route::post(':version/city','api/:version.address/city');//获取省市区地址信息
Route::post(':version/comment_create','api/:version.comment/create');//创建评论
Route::post(':version/comment_list','api/:version.comment/index');//商品评论列表
Route::post(':version/file_upload','api/:version.uploads/uploadData');//单文件上传
Route::post(':version/balance','api/:version.pay/balance');//余额支付
Route::post(':version/pay','api/:version.pay/index');//微信支付
Route::post(':version/TiPay','api/:version.pay/zOrderPay');//自提微信支付
Route::post(':version/freight','api/:version.order/freight');//结算运费
Route::post(':version/getUserPhone','api/:version.user/getUserPhone');//绑定手机号码
Route::post(':version/question_list','api/:version.question/index');//问卷调查列表
Route::post(':version/create_question','api/:version.question/create');//提交问卷调查
Route::post(':version/category_list','api/:version.material/category');//获取分类
Route::post(':version/search_category','api/:version.material/category2');//获取分类
Route::post(':version/material_list','api/:version.material/index');//素材列表
Route::post(':version/getDateList','api/:version.material/getDateList');//获取视频日期列表
Route::post(':version/video_list','api/:version.material/video');//获取视频日期列表
Route::post(':version/video_details','api/:version.material/videoDetails');//获取视频详情
Route::post(':version/videoComment','api/:version.material/videoComment');//创建视频评论
Route::post(':version/video_comment_list','api/:version.material/videoCommentList');//视频评论列表
Route::post(':version/videoLike','api/:version.material/videoLike');//视频点赞/取消点赞
Route::post(':version/friend_list','api/:version.material/friend');//朋友圈素材列表
Route::post(':version/friend_like','api/:version.material/friendLike');//点赞/取消点赞
Route::post(':version/friend_collection','api/:version.material/friendCollection');//收藏/取消收藏
Route::post(':version/agent_create','api/:version.agent/create');//代理申请
Route::post(':version/login_agent','api/:version.agent/login');//代理登陆
Route::post(':version/agent_details','api/:version.agent/details');//代理详情
Route::post(':version/rechargeMoney','api/:version.agent/rechargeMoney');//代理充值金额
Route::post(':version/recharge_money_pay','api/:version.agent/rechargeMoneyPay');//代理充值支付
Route::post(':version/updatePwdAgent','api/:version.agent/updatePwd');//代理修改密码
Route::post(':version/agentCollectList','api/:version.agent/agentCollect');//代理修改密码
Route::post(':version/agentCollectList','api/:version.agent/agentCollect');//代理修改密码
Route::post(':version/agent_stock_apple','api/:version.agent/agentStockApple');//代理进货申请
Route::post(':version/agent_stock_goods','api/:version.agent/agentStockGoods');//代理商品库存记录
Route::post(':version/agent_stock_order_list','api/:version.agent/agentStockOrderList');//代理进货申请记录
Route::post(':version/stock_order_pay','api/:version.agent/agentStockPay');//代理进货申请记录
Route::post(':version/agent_withdraw_create','api/:version.agent/withdraw');//代理提现申请
Route::post(':version/bank_list','api/:version.bank/index');//获取银行列表
Route::post(':version/agent_order','api/:version.agent/agentOrder');//获取用户订单列表
Route::post(':version/agentRecommend','api/:version.agent/agentRecommend');//获取用户订单列表
Route::post(':version/withdrawList','api/:version.agent/withdrawList');//获取提现列表
Route::post(':version/team','api/:version.user/team');//获取普通用户团队列表
Route::post(':version/commission','api/:version.user/Commission');//获取普通用户分销记录
Route::post(':version/questionGoods','api/:version.question/newGoods');//获取最新一次得检测商品
Route::post(':version/questionCart','api/:version.question/newGoodsCart');//检测商品一键加入购物车
Route::post(':version/authBook','api/:version.agent/authBook');//获取代理授权书
Route::post(':version/agentLevel','api/:version.agent/agentLevel');//获取代理授权书
Route::post(':version/adList','api/:version.ad/index');//广告列表
Route::post(':version/agentQrcode','api/:version.agent/agsentQrcode');//获取代理推荐二维码
Route::post(':version/agentsQrcode','api/:version.agent/agentsQrcode');//获取代理店铺二维码
Route::post(':version/updateAuthBook','api/:version.agent/updateAuthBook');//更新代理授权证书
Route::post(':version/watch','api/:version.user/watch');//收取商品围观
Route::post(':version/notify','api/:version.notify/index');//微信支付异步
Route::post(':version/zt','api/:version.notifyss/index');//自提订单异步
Route::post(':version/chongzhi_notify','api/:version.notifys/index');//微信支付异步2
Route::post(':version/getAgentInfo','api/:version.agent/getAgentInfo');//获取代理提交详情
Route::post(':version/getLatelyGoods','api/:version.goods/getLatelyGoods');//最近购买过该商品的用户
Route::post(':version/rechargesLog','api/:version.agent/rechargeMoneyLog');//代理充值记录
Route::post(':version/logistics','api/:version.order/logistics');//查询物流信息
Route::post(':version/z_logistics','api/:version.order/logistics2');//查询物流信息
Route::post(':version/refresh','api/:version.token/refresh');//刷新token
Route::post(':version/getAgentCode','api/:version.agent/getAgentCode');//获取代理邀请码code
Route::post(':version/getTeamAchievement','api/:version.agent/getTeamAchievement');//获取代理团队进货记录
Route::post(':version/cheshi','api/:version.cheshi/index');//测试
Route::post(':version/agent_cheshi','api/:version.cheshi/agent');//测试
Route::post(':version/agent_update_cheshi','api/:version.cheshi/agentUpdate');//测试
Route::post(':version/ZOrderAgent','api/:version.ZOrderAgent/index');//自提订单列表
Route::post(':version/z_order_agent_details','api/:version.ZOrderAgent/details');//自提订单列表
Route::post(':version/z_order_agent_create','api/:version.ZOrderAgent/create');//自提订单列表
